version: "2.3"

services:
    svh_gateway_service-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/svh_gateway_service/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/svh_gateway_service:rw
        ports:
          - 8080:8080
        working_dir: /svh_gateway_service
        entrypoint:
          - ./tests/run_as_user.sh
